# Jekyll configuration

name: VO Station
name_en: Viggo Mortensen, Orlando Bloom

# url is currently only used for the RSS feed in feed.xml
url: https://junesirius.github.io
baseurl: "/VOStation"

## default date_format
date_format: 
  title: "%m-%d-%Y"
  archive: "%m-%d"
  categories: "%m-%d-%Y"
  tags: "%m-%d-%Y"

# Language
lan: "cn" 

paginate: 10

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE', "*.bak"]

permalink: /:year/:title